// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: authms.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthMsClient is the client API for AuthMs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthMsClient interface {
	// Generates a new RT and a JWT
	GetNewRT(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Tokens, error)
	// After thic call the old JWT should revoked and a new jwt are generated
	// The call can be used e.g. when the old JWT will be expired soon
	ReplaceRT(ctx context.Context, in *JWT, opts ...grpc.CallOption) (*JWT, error)
	// Geneterates a JWT based on the RT, if RT is invalid empty jwt is returned
	GetNewJWT(ctx context.Context, in *RT, opts ...grpc.CallOption) (*JWT, error)
	Revoke(ctx context.Context, in *Tokens, opts ...grpc.CallOption) (*RevokeResponse, error)
	// Get a user based on the jwt
	GetUser(ctx context.Context, in *JWT, opts ...grpc.CallOption) (*User, error)
}

type authMsClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthMsClient(cc grpc.ClientConnInterface) AuthMsClient {
	return &authMsClient{cc}
}

func (c *authMsClient) GetNewRT(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Tokens, error) {
	out := new(Tokens)
	err := c.cc.Invoke(ctx, "/AuthMs/GetNewRT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMsClient) ReplaceRT(ctx context.Context, in *JWT, opts ...grpc.CallOption) (*JWT, error) {
	out := new(JWT)
	err := c.cc.Invoke(ctx, "/AuthMs/ReplaceRT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMsClient) GetNewJWT(ctx context.Context, in *RT, opts ...grpc.CallOption) (*JWT, error) {
	out := new(JWT)
	err := c.cc.Invoke(ctx, "/AuthMs/GetNewJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMsClient) Revoke(ctx context.Context, in *Tokens, opts ...grpc.CallOption) (*RevokeResponse, error) {
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, "/AuthMs/Revoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMsClient) GetUser(ctx context.Context, in *JWT, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/AuthMs/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthMsServer is the server API for AuthMs service.
// All implementations must embed UnimplementedAuthMsServer
// for forward compatibility
type AuthMsServer interface {
	// Generates a new RT and a JWT
	GetNewRT(context.Context, *Credentials) (*Tokens, error)
	// After thic call the old JWT should revoked and a new jwt are generated
	// The call can be used e.g. when the old JWT will be expired soon
	ReplaceRT(context.Context, *JWT) (*JWT, error)
	// Geneterates a JWT based on the RT, if RT is invalid empty jwt is returned
	GetNewJWT(context.Context, *RT) (*JWT, error)
	Revoke(context.Context, *Tokens) (*RevokeResponse, error)
	// Get a user based on the jwt
	GetUser(context.Context, *JWT) (*User, error)
	mustEmbedUnimplementedAuthMsServer()
}

// UnimplementedAuthMsServer must be embedded to have forward compatible implementations.
type UnimplementedAuthMsServer struct {
}

func (UnimplementedAuthMsServer) GetNewRT(context.Context, *Credentials) (*Tokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewRT not implemented")
}
func (UnimplementedAuthMsServer) ReplaceRT(context.Context, *JWT) (*JWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceRT not implemented")
}
func (UnimplementedAuthMsServer) GetNewJWT(context.Context, *RT) (*JWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewJWT not implemented")
}
func (UnimplementedAuthMsServer) Revoke(context.Context, *Tokens) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedAuthMsServer) GetUser(context.Context, *JWT) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAuthMsServer) mustEmbedUnimplementedAuthMsServer() {}

// UnsafeAuthMsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthMsServer will
// result in compilation errors.
type UnsafeAuthMsServer interface {
	mustEmbedUnimplementedAuthMsServer()
}

func RegisterAuthMsServer(s grpc.ServiceRegistrar, srv AuthMsServer) {
	s.RegisterService(&AuthMs_ServiceDesc, srv)
}

func _AuthMs_GetNewRT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthMsServer).GetNewRT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthMs/GetNewRT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthMsServer).GetNewRT(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthMs_ReplaceRT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthMsServer).ReplaceRT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthMs/ReplaceRT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthMsServer).ReplaceRT(ctx, req.(*JWT))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthMs_GetNewJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthMsServer).GetNewJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthMs/GetNewJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthMsServer).GetNewJWT(ctx, req.(*RT))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthMs_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthMsServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthMs/Revoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthMsServer).Revoke(ctx, req.(*Tokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthMs_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JWT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthMsServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthMs/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthMsServer).GetUser(ctx, req.(*JWT))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthMs_ServiceDesc is the grpc.ServiceDesc for AuthMs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthMs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthMs",
	HandlerType: (*AuthMsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNewRT",
			Handler:    _AuthMs_GetNewRT_Handler,
		},
		{
			MethodName: "ReplaceRT",
			Handler:    _AuthMs_ReplaceRT_Handler,
		},
		{
			MethodName: "GetNewJWT",
			Handler:    _AuthMs_GetNewJWT_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _AuthMs_Revoke_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthMs_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authms.proto",
}
